version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/bitly
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
